sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
    - develop
    - dev-lib-test
php:
  - 5.3
  - 7.1
env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0
matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0
before_script:
  - >-
    curl
    https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar
    > /tmp/wp-cli.phar
  - chmod +x /tmp/wp-cli.phar
  - >-
    bash .dev/lib/install-wp-tests.sh wordpress_test root '' localhost
    $WP_VERSION
  - 'export PATH="$HOME/.composer/vendor/bin:$PATH"'
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - >
    composer global require wp-coding-standards/wpcs

    phpcs --config-set installed_paths
    $HOME/.composer/vendor/wp-coding-standards/wpcs
script:
  - phpcs --standard=.dev/lib/phpcs.ruleset.xml $(find . -name '*.php')
  - phpunit -c .dev/lib/phpunit.xml.dist
